/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./web/templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "gold": "#fc7218",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#bec6e0",
        "inverse-surface": "#213145",
        "navy": "#131b2e",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#592200",
        "on-secondary-fixed": "#341100",
        "on-secondary-fixed-variant": "#793100",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#45464d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#008cc7",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary-fixed-variant": "#004c6e",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "secondary": "#9f4200",
        "secondary-container": "#fc7218",
        "secondary-fixed": "#ffdbcb",
        "secondary-fixed-dim": "#ffb692",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-tint": "#565e74",
        "surface-variant": "#d3e4fe",
        "tertiary": "#000000",
        "tertiary-container": "#001e2f",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#89ceff",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            color: theme("colors.on-surface"),
            fontFamily: theme("fontFamily.body").join(","),
            fontSize: "1.0625rem",
            lineHeight: "1.8",
            maxWidth: "none",
            a: { color: theme("colors.secondary"), textDecoration: "none", "&:hover": { textDecoration: "underline" } },
            h1: { fontFamily: theme("fontFamily.headline").join(","), fontWeight: "900", color: theme("colors.on-surface") },
            h2: { fontFamily: theme("fontFamily.headline").join(","), fontWeight: "800", color: theme("colors.on-surface"), marginTop: "2rem" },
            h3: { fontFamily: theme("fontFamily.headline").join(","), fontWeight: "700", color: theme("colors.on-surface") },
            blockquote: { borderLeftColor: theme("colors.secondary"), backgroundColor: theme("colors.surface-container-low"), padding: "1rem 1.5rem", borderRadius: "0.25rem", fontStyle: "normal", color: theme("colors.on-surface") },
            code: { backgroundColor: theme("colors.surface-container-high"), padding: "0.15rem 0.4rem", borderRadius: "0.2rem", fontWeight: "500" },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: { backgroundColor: theme("colors.primary-container"), color: "#e2e8f0" },
          },
        },
      }),
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
  ],
};
